services:
  - type: web
    name: matrix-osint
    env: node
    plan: free
    rootDir: .
    buildCommand: ""
    startCommand: node backend/server.js
    autoDeploy: true
    envVars:
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_RESET_KEY
        sync: false
      - key: VERIPHONE_API_KEY
        sync: false
