services:
  - type: web
    name: matrix-osint
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: VERIPHONE_API_KEY
        sync: false
